login_check:
    path:   /login_check

logout:
    path:   /logout

chiave_gallery:
    resource: "@ChiaveGalleryBundle/Controller"
    type:     annotation
    prefix:   /

chiave_core_bundle:
    resource: "@ChiaveCoreBundle/Controller"
    type:     annotation
    prefix:   /

#must be last!
chiave_static:
    resource: "@ChiaveStaticBundle/Controller/"
    type:     annotation
    prefix:   /
