<?php

namespace Chiave\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KategoriaRepository extends EntityRepository
{
}
